work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 300 
  data_path: ../pose_train_data.npy
  label_path: ../pose_train_label.pkl
test_feeder_args:
  data_path: ../pose_val_data.npy
  label_path: ../pose_val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 40
test_batch_size: 40

#optim
base_lr: 0.25
step: [400,500,600]
num_epoch: 700



