# command line: vis_bruce.py

config: config/st_gcn/kinetics-skeleton/demo.yaml
device:
- 0
ignore_weights: []
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 4
print_log: true
save_log: true
use_gpu: true
weights: ./models/epoch970_model.pt
work_dir: ./work_dir/tmp
