weights: ./models/epoch970_model.pt

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [0]
